services:
  ruzenbot:
    image: ruzen42/ruzenbot:latest
    container_name: ruzenbot-botnet
    env_file:
      - .env  
    depends_on:
      - shellrunner
      - github-api 
      - ruzenbot-db
    networks:
      - botnet
    restart: unless-stopped
    
  shellrunner:
    image: ruzen42/shell-runner:latest
    container_name: shellrunner-botnet
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - botnet
  github-api:
    image: ruzen42/github-api:latest
    container_name: github-api-botnet
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - botnet

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ruzenbot:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d botdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - botnet 

  ruzenbot-db:
    image: ruzen42/ruzenbot-db 
    container_name: ruzenbot-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Host=postgres;Port=5432;Database=botdb;Username=postgres;Password=postgres;Pooling=true;
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - botnet
    restart: unless-stopped

volumes:
  ruzenbot:
    
networks:
  botnet:
    driver: bridge
