#! /nix/store/xy4jjgw87sbgwylm5kn047d9gkbhsr9x-bash-5.2p37/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/qb3ag0r154g8vpifnlwha3gg4i5n71lz-python3.12-ueberzug-18.1.9/bin'':'/':'}
PATH='/nix/store/qb3ag0r154g8vpifnlwha3gg4i5n71lz-python3.12-ueberzug-18.1.9/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/fx0cjyvqjmfnbqxcd60bwaf36ak16q2q-pciutils-3.13.0/bin'':'/':'}
PATH='/nix/store/fx0cjyvqjmfnbqxcd60bwaf36ak16q2q-pciutils-3.13.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
exec -a "$0" "/nix/store/qplcllg8rwrgg7ylyz4a3gkiypry5vnc-neofetch-unstable-2021-12-10/bin/.neofetch-wrapped"  "$@" 
