name:                ruzenbot
version:             0.1.0.0
github:              "ruzen42/ruzenbot"
license:             BSD-3-Clause
author:              "ruzen42"
maintainer:          "malledeferlive@gmail.com"
copyright:           "2025 ruzen42"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Telegram bot 
category:            Web

description:         Please see the README on GitHub at <https://github.com/ruzen42/ruzenbot#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ruzenbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ruzenbot
    - telegram-bot-simple

tests:
  ruzenbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ruzenbot
    - telegram-bot-simple
