<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishTrimmed>false</PublishTrimmed>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="dotenv.net" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.7.25380.108" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="NeoSimpleLogger" Version="1.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4-beta1" />
    <PackageReference Include="Telegram.Bot" Version="22.6.1-dev.2" />
  </ItemGroup>
</Project>
