<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.32.0-rc2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.7.25380.108" />
    <PackageReference Include="MinecraftRcon" Version="1.0.1" />
    <PackageReference Include="NeoSimpleLogger" Version="1.4.0" />
    <PackageReference Include="OpenWeatherAPI" Version="1.0.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.0-preview.7.25380.108" />
    <PackageReference Include="Telegram.Bot" Version="22.6.1-dev.2" />
  </ItemGroup>

</Project>
